### ISSUE TITLE
If two tabs are blocked, overriding won't bring you back to the original page.

### ISSUE THREAD

**Issue by Walkier** [ChrisSmith2/YouTube-Time#2]
Let's say you ran out time but have two tabs (a & b) each playing a different video. Then you click tab a then tab b, so both become blocked. When you go to override tab a, tab b's url will load up instead.
It is really reproducible on my end but I don't know about other users.

Anyway, it seems like Chrome's store has blocked comments during this period. So I'm here to say I'm glad you found use for my code. Good luck!

**Comment by ChrisSmith2** [comment]
Thanks for reporting this issue. Previously the video url was being stored in a single variable, so it would be overridden if multiple tabs became blocked at the same time. Now a video url can be stored for each YouTube tab, so this should be fixed in the latest version (1.4.3).
